from os.path import join as j

configfile: "../config.yaml"


#
# Directories
#
DATA_DIR = config["data_dir"]
LEGV2_DATA_DIR = j(config["legcit_data_dir"])
SUPP_DATA_DIR = j(config["supp_data_dir"])


# ================
# Source
# ================
LEGV2_RAW_DATA_DIR = SUPPD_DATA_DIR
LEGV2_CITATION = j(LEGV2_DATA_DIR, "Legal_Citation_Dict.json")
LEGV2_CITATION_INFO = j(LEGV2_DATA_DIR, "Citation_Info_Dict.json")
LEGV2_COURT_HIERARCHY = j(LEGV2_RAW_DATA_DIR, "court_hierarchy.json")

# ================
# Preprocessed
# ================
LEGV2_PREPROC_DATA_DIR = j(DATA_DIR, "legcitv2", "preprocessed")
LEGV2_PAPER_TABLE = j(LEGV2_PREPROC_DATA_DIR, "paper_table.csv")
LEGV2_CIATAION_NET = j(LEGV2_PREPROC_DATA_DIR, "citation_net.npz")
LEGV2_PAPER_CATEGORY_TABLE= j(LEGV2_PREPROC_DATA_DIR, "paper_category_table.csv")
LEGV2_CATEGORY_TABLE= j(LEGV2_PREPROC_DATA_DIR, "category_table.csv")

# Supplementary
LEGV2_COURT_TABLE_FILE = j(LEGV2_PREPROC_DATA_DIR, "court_table.csv")

rule construct_citation_net:
    input:
        node_data_file=LEGV2_CITATION_INFO,
        link_data_file=LEGV2_CITATION,
        court_data_file=LEGV2_COURT_HIERARCHY,
    output:
        net_file=LEGV2_CIATAION_NET,
        node_table_file=LEGV2_PAPER_TABLE,
        court_table_file=LEGV2_COURT_TABLE_FILE,
    script:
        "workflow/const-cit-net.py"



rule construct_category_table:
    input:
        input_file=LEGV2_PAPER_TABLE,
        court_hierarchy_file=LEGV2_COURT_HIERARCHY
    output:
        output_paper_category_table_file = LEGV2_PAPER_CATEGORY_TABLE,
        output_category_table_file = LEGV2_CATEGORY_TABLE
    script:
        "workflow/make_category_table.py"

rule all:
    input:
        LEGV2_PAPER_TABLE,
        LEGV2_CIATAION_NET,
        LEGV2_COURT_TABLE_FILE,
        LEGV2_PAPER_CATEGORY_TABLE,
        LEGV2_CATEGORY_TABLE
