from os.path import join as j

configfile: "../config.yaml"


#
# Directories
#
WOS_DATA_DIR = j(config["data_dir"])


# ================
# Source
# ================
WOS_JSON_DIR = config["wos_json_dir"]
WOS_CITATION_TABLE = j(WOS_JSON_DIR, "citeEdges.csv", "citeEdges.csv.gz")


# ================
# Preprocessed
# ================
WOS_PREPROC_DATA_DIR = j(WOS_DATA_DIR, "wos", "preprocessed")
WOS_PAPER_TABLE = j(WOS_PREPROC_DATA_DIR, "paper_table.csv")
WOS_CITATION_NET = j(WOS_PREPROC_DATA_DIR, "citation_net.npz")
#WOS_AUTHOR_TABLE = j(WOS_PREPROC_DATA_DIR, "author_table.csv")
#WOS_PAPER_AUTHOR_NET = j(WOS_PREPROC_DATA_DIR, "paper_author_net.npz")
#WOS_COURT_TABLE_FILE = j(WOS_PREPROC_DATA_DIR, "court_table.csv")


# =================
# Intermediaries
# =================
WOS_PAPER_JOURNAL_TABLE = j(
    WOS_PREPROC_DATA_DIR, "supp", "paper-journal-table.csv"
)


rule construct_wos_paper_journal_table:
    input:
        json_file_dir=WOS_JSON_DIR,
    output:
        output_file=WOS_PAPER_JOURNAL_TABLE,
    script:
        "workflow/construct-paper-journal-table.py"

rule construct_wos_citation_net:
    input:
        citation_table_file=WOS_CITATION_TABLE,
        paper_table_file=WOS_PAPER_JOURNAL_TABLE,
    output:
        net_file=WOS_CITATION_NET,
        node_file=WOS_PAPER_TABLE,
    script:
        "workflow/construct-paper-citation-net.py"

rule all:
    input:
        WOS_PAPER_TABLE,
        WOS_CITATION_NET
